name: Build data

on: [push]

jobs:
  build:
    name: Docker image build CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
      - name: 🏃 Run full
        #if: steps.extract_branch.outputs.branch == 'master' || steps.extract_branch.outputs.branch == 'dev'
        run: make all-step0 recipe-run watch-run STORAGE_ACCESS_KEY=$STORAGE_ACCESS_KEY STORAGE_SECRET_KEY=$STORAGE_SECRET_KEY CHUNK_SIZE=5000 ES_THREADS=2 RECIPE_THREADS=2 ES_MEM=4000m
        env:
          STORAGE_ACCESS_KEY: ${{ secrets.STORAGE_ACCESS_KEY }}
          STORAGE_SECRET_KEY: ${{ secrets.STORAGE_SECRET_KEY }}
          #- name: 🏃 Small dataset
          #  if: steps.extract_branch.outputs.branch != 'master' && steps.extract_branch.outputs.branch != 'dev'
          #  run: make all-step0 recipe-run watch-run FILES_TO_PROCESS=deces-2020-m01.txt.gz STORAGE_ACCESS_KEY=$STORAGE_ACCESS_KEY STORAGE_SECRET_KEY=$STORAGE_SECRET_KEY RECIPE_THREADS=2
          #  env:
          #    STORAGE_ACCESS_KEY: ${{ secrets.STORAGE_ACCESS_KEY }}
          #    STORAGE_SECRET_KEY: ${{ secrets.STORAGE_SECRET_KEY }}
          #- name: 🏃 Run full
          #  if: steps.extract_branch.outputs.branch == 'master' || steps.extract_branch.outputs.branch == 'dev'
          #  run: make all-step0 recipe-run watch-run STORAGE_ACCESS_KEY=$STORAGE_ACCESS_KEY STORAGE_SECRET_KEY=$STORAGE_SECRET_KEY RECIPE_THREADS=2
          #  env:
          #    STORAGE_ACCESS_KEY: ${{ secrets.STORAGE_ACCESS_KEY }}
          #    STORAGE_SECRET_KEY: ${{ secrets.STORAGE_SECRET_KEY }}
